import streamlit as st
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

st.title("Interactief Data Dashboard")

uploaded_file = st.file_uploader("Upload je Excel/CSV bestand", type=["csv", "xlsx"])

if uploaded_file is not None:
    if uploaded_file.name.endswith('.csv'):
        combined_df = pd.read_csv(uploaded_file)
    else:
        combined_df = pd.read_excel(uploaded_file)

    # Data voorbereiden
    combined_df['Date and time'] = pd.to_datetime(combined_df['Date and time'], format='%d-%m-%Y %H:%M:%S.%f')
    combined_df['kind'] = combined_df['Location'].str.split('/').str[-1].str.strip()
    combined_df['Date'] = combined_df['Date and time'].dt.date
    combined_df['Time'] = combined_df['Date and time'].dt.time
    combined_df['Prioriteit'] = np.where(
        combined_df['Flow name'].str.contains('MDDG_prioriteit_Medium_alarm_Raise'), 'Medium',
        np.where(
            combined_df['Flow name'].str.contains('MDDG_prioriteit_Hoog_alarm_Raise'), 'High',
            'Overig'
        )
    )
    combined_df['id'] = combined_df['Flow execution id']
    combined_df['Message'] = combined_df['Autogenerated message']
    combined_df = combined_df.drop(columns=['Flow name', 'Flow execution id', 'Location', 'Flow group', 'Autogenerated message'])

    # Data splitsen
    split_date = pd.to_datetime('2024-11-26').date()
    combined2_df = combined_df[combined_df['Date'] > split_date].copy()
    combined_df = combined_df[combined_df['Date'] < split_date].copy()

    finished_df = combined_df[combined_df['Status'] == 'Finished']
    deliverd_df = combined_df[combined_df['Status'] == 'Delivered']
    finished2_df = combined2_df[combined2_df['Status'] == 'Finished']
    deliverd2_df = combined2_df[combined2_df['Status'] == 'Delivered']

    df = pd.DataFrame(finished_df)
    dfd = pd.DataFrame(deliverd_df)
    df2 = pd.DataFrame(finished2_df)
    dfd2 = pd.DataFrame(deliverd2_df)

    # Datum selectie door gebruiker
    min_date = combined_df['Date'].min()
    max_date = combined_df['Date'].max()
    selected_date = st.date_input("Selecteer datum voor grafiek:", value=max_date, min_value=min_date, max_value=max_date)

    # Filter op geselecteerde datum
    filtered_finished = df[df['Date'] == selected_date]
    filtered_delivered = dfd[dfd['Date'] == selected_date]

    # Groepeer per datum
    delivered_counts = filtered_delivered.groupby('Date').size()
    finished_counts = filtered_finished.groupby('Date').size()

    plot_df = pd.DataFrame({
        'Delivered': delivered_counts,
        'Finished': finished_counts
    }).fillna(0)

    avg_delivered = plot_df['Delivered'].mean() if not plot_df.empty else 0
    avg_finished = plot_df['Finished'].mean() if not plot_df.empty else 0

    # Plotten
    plt.figure(figsize=(12, 6))
    plot_df.plot(kind='line', marker='o', ax=plt.gca())
    plt.axhline(y=avg_delivered, color='blue', linestyle='--', label=f'Gem. Delivered ({avg_delivered:.1f})')
    plt.axhline(y=avg_finished, color='orange', linestyle='--', label=f'Gem. Finished ({avg_finished:.1f})')
    plt.title(f'Aantal meldingen per dag (Delivered & Finished) op {selected_date}')
    plt.xlabel('Datum')
    plt.ylabel('Aantal meldingen')
    plt.grid(True)
    plt.xticks(rotation=45)
    plt.tight_layout()
    plt.legend(title='Status')
    
    st.pyplot(plt)
